name: Deploy AND DELETE Redis

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: generate hash
        run: |
          HASH=$(date | md5sum | cut -d ' ' -f 1)
          ZIP_FILE_NAME="redis---$HASH"
          echo "HASH=$HASH" >> $GITHUB_ENV
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV

      - name: install system dependencies
        run: sudo apt install -y qemu-user-static binfmt-support

      - name: build docker image
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          sudo apt install -y qemu-user-static binfmt-support
          cd redis
          echo "zipFileName ${{ env.ZIP_FILE_NAME }}"
          zipFileName=${{ env.ZIP_FILE_NAME }}
          /bin/bash ./scripts/docker/export-prod.sh $zipFileName

      - name: deploy
        run: |
          cd redis
          zipFileName=${{ env.ZIP_FILE_NAME }}
          zip -r $zipFileName.zip docker-image.tar meta.json
          echo "${{ secrets.EC2_RSA }}" > ./identityFile.txt
          chmod 400 ./identityFile.txt
          scp -o "StrictHostKeyChecking=no" -i ./identityFile.txt -r ./$zipFileName.zip ubuntu@ec2-13-40-134-151.eu-west-2.compute.amazonaws.com:/home/ubuntu/departure-lounge/
